//PatientId -> email, name, cpf
//PsychologistId -> chave pix, valor da consulta, cpf

namespace Api.Payment.Services;
using Api.Payment.Interfaces;
using Api.Payment.DTOs.Entry;
using Api.Payment.DTOs.Return;
using Api.Payment.Models;
using Shared.DTOs.Result;

public class PaymentService : IPaymentInterface
{
    public async Task<Result<PaymentChargeCreatedDto>> CreatePaymentCharge(EntryDataPayment dto)
    {
        // Implement the logic to create a payment charge here
        // For now, we will return a dummy result for demonstration purposes

        var paymentChargeCreatedDto = new PaymentChargeCreatedDto
        {
            PaymentChargeId = 1, // This should be generated by your payment system
            QrCode = "dummy_qr_code", // This should be generated by your payment system
            QrCodeBase64 = "dummy_qr_code_base64", // This should be generated by your payment system
            Amount = 100, // Assuming dto has an Amount property
            Status = PaymentChargeStatus.Pending // Assuming you have a PaymentChargeStatus enum
        };

        var result = new Result<PaymentChargeCreatedDto>
        {
            Success = true,
            Data = paymentChargeCreatedDto,
            Message = "Payment charge created successfully."
        };
        return result;
    }
}